version: 2
jobs:
  build:
    docker:
      - image: framgia/laravel-workspace
      - image: circleci/node:9.2.0
      - image: circleci/mysql:5.7.18
        environment:
          MYSQL_DATABASE: tagvote_test
          MYSQL_USER: tagvote_test
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: password

    working_directory: ~/repo

    steps:
      - checkout

      - run: chmod -R 777 storage
      - run: cp .env.dusk.testing .env

      - restore_cache:
          name: Restore composer cache
          keys:
          - composer-{{ checksum "composer.json" }}
          - composer-
      - run: composer install -n --prefer-dist
      - save_cache:
          name: Store composer cache
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor
      # Yarn
      - restore_cache:
          name: Restore yarn cache
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "composer.json" }}

      - run: npm run production
      - run: php artisan migrate --database=mysql_test
      # run tests!
      - run:
          command: |
            mkdir -p /phpunit &&
            php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=phpunit/coverage-clover.xml --coverage-html=phpunit/coverage
      - store_test_results:
          path: /phpunit
      - store_artifacts:
          path: /phpunit